In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('Social_Network_Ads.csv')
df

User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [3]:
df.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [4]:
df.tail()

User ID  Gender  Age  EstimatedSalary  Purchased
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

In [5]:
df.shape

(400, 5)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   User ID          400 non-null    int64 
 1   Gender           400 non-null    object
 2   Age              400 non-null    int64 
 3   EstimatedSalary  400 non-null    int64 
 4   Purchased        400 non-null    int64 
dtypes: int64(4), object(1)
memory usage: 15.8+ KB


In [7]:
df.describe()

User ID         Age  EstimatedSalary   Purchased
count  4.000000e+02  400.000000       400.000000  400.000000
mean   1.569154e+07   37.655000     69742.500000    0.357500
std    7.165832e+04   10.482877     34096.960282    0.479864
min    1.556669e+07   18.000000     15000.000000    0.000000
25%    1.562676e+07   29.750000     43000.000000    0.000000
50%    1.569434e+07   37.000000     70000.000000    0.000000
75%    1.575036e+07   46.000000     88000.000000    1.000000
max    1.581524e+07   60.000000    150000.000000    1.000000

In [18]:
x = df.iloc[:, 0:4]
y = df.iloc[:, 4:5]

In [19]:
x

User ID  Gender  Age  EstimatedSalary
0    15624510    Male   19            19000
1    15810944    Male   35            20000
2    15668575  Female   26            43000
3    15603246  Female   27            57000
4    15804002    Male   19            76000
..        ...     ...  ...              ...
395  15691863  Female   46            41000
396  15706071    Male   51            23000
397  15654296  Female   50            20000
398  15755018    Male   36            33000
399  15594041  Female   49            36000

[400 rows x 4 columns]

In [20]:
y

Purchased
0            0
1            0
2            0
3            0
4            0
..         ...
395          1
396          1
397          1
398          0
399          1

[400 rows x 1 columns]

In [21]:
y.Purchased.value_counts()

Purchased
0    257
1    143
Name: count, dtype: int64

In [22]:
X = pd.get_dummies(x)

In [23]:
X

User ID  Age  EstimatedSalary  Gender_Female  Gender_Male
0    15624510   19            19000          False         True
1    15810944   35            20000          False         True
2    15668575   26            43000           True        False
3    15603246   27            57000           True        False
4    15804002   19            76000          False         True
..        ...  ...              ...            ...          ...
395  15691863   46            41000           True        False
396  15706071   51            23000          False         True
397  15654296   50            20000           True        False
398  15755018   36            33000          False         True
399  15594041   49            36000           True        False

[400 rows x 5 columns]

In [24]:
from sklearn.model_selection import train_test_split

In [25]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=0)

In [26]:
from sklearn.preprocessing import StandardScaler

In [27]:
sc = StandardScaler()

In [28]:
X_train = sc.fit_transform(X_train)

In [29]:
X_test = sc.transform(X_test)

In [30]:
X_train

array([[-0.37311852,  1.92295008,  2.14601566, -1.02532046,  1.02532046],
       [-1.22319878,  2.02016082,  0.3787193 ,  0.97530483, -0.97530483],
       [-0.596909  , -1.3822153 , -0.4324987 ,  0.97530483, -0.97530483],
       ...,
       [-1.4157145 , -0.21568634, -0.51941492, -1.02532046,  1.02532046],
       [ 1.20822913, -1.09058306, -0.46147078,  0.97530483, -0.97530483],
       [ 1.46809058, -1.18779381,  1.3927418 ,  0.97530483, -0.97530483]])

In [31]:
from sklearn.linear_model import LogisticRegression

In [32]:
classifier = LogisticRegression(random_state=0)

In [33]:
classifier.fit(X_train,y_train)

C:\Users\vkubade\AppData\Local\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1300: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression()

In [34]:
y_pred = classifier.predict(X_test)

In [36]:
y_pred

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1], dtype=int64)

In [38]:
classifier.score(X_test,y_test)

0.925

In [39]:
from sklearn.metrics import confusion_matrix,classification_report

In [40]:
cm = confusion_matrix(y_test,y_pred)

In [41]:
cm

array([[57,  1],
       [ 5, 17]], dtype=int64)

In [42]:
cl_report = classification_report(y_test,y_pred)

In [44]:
print(cl_report)

              precision    recall  f1-score   support

           0       0.92      0.98      0.95        58
           1       0.94      0.77      0.85        22

    accuracy                           0.93        80
   macro avg       0.93      0.88      0.90        80
weighted avg       0.93      0.93      0.92        80



In [45]:
tp,fn,fp,tn = confusion_matrix(y_test,y_pred,labels=[0,1]).reshape(-1)

In [49]:
print('Outcome Values:\n TP FN FP TN\n',tp,fn,fp,tn)

Outcome Values:
 TP FN FP TN
 57 1 5 17


In [54]:
acc = ((tp+tn)/(tp+fn+fp+tn))
error = 1-acc
precision = tp/(tp+fp)
recall = tp/(tp+fn)

In [55]:
print('Accuracy:',acc)

Accuracy: 0.925


In [56]:
print('Error Rate:',error)

Error Rate: 0.07499999999999996


In [57]:
print('Precision:',precision)

Precision: 0.9193548387096774


In [58]:
print('Recall:',recall)

Recall: 0.9827586206896551
